# Importing required libraries

`sqlalchemy` is a "toolkit" that allows access to SQL databases through python. SQL tables can be queried and directly brought to python objects without the need of an intermediate export-import step (such as creating a csv from MySQL Workbench).

Converting data between incompatible type systems is called Object-relational mapping, so you might see `sqlalchemy` referred to as an ORM tool.

Here we'll see the basic workflow for connecting to a local database and transforming it to a `pandas` dataframe. Explore more features in the docs https://www.sqlalchemy.org/

MySQL has its own ORM tool for interacting with python, called `Connector/Python` (https://dev.mysql.com/doc/connector-python/en/connector-python-introduction.html). The advantage of `sqlalchemy` is that it can also work with other DBMS such as Oracle, Postgres, etc.

In [ ]:
#!pip3 install pymsql

#we need to install into our Conda DA_Env :

#conda install -c anaconda pymysql

#and

# conda install -c anaconda sqlalchemy

In [1]:
import pandas as pd
import getpass
import sqlalchemy as sa

# To connect and extract tables from SQL database.
Hint: the password is needed fot the DB user

In [2]:
driver = 'mysql+pymysql'
user = 'root'
password = getpass.getpass(prompt='Your password:'"")
ip = '127.0.0.1'

Your password:········

In [3]:
connection_string = f'{driver}://{user}:{password}@{ip}'

In [ ]:
connection_string

In [4]:
db_connection = sa.create_engine(connection_string)

In [5]:
insp = sa.inspect(db_connection)
db_list = insp.get_schema_names()
print(db_list)

['bank', 'information_schema', 'lab_db', 'lab_db_python_sql', 'lab_db_python_sql2', 'lab_db_test_commands', 'lab_group_by_db', 'mysql', 'Olist', 'performance_schema', 'publications', 'sakila', 'skila_analytics', 'sys']

 Retreiving data into python object (without Pandas)

In [7]:
result = db_connection.execute('SELECT * FROM bank.loan')
print (type(result))
for row in result:
    #print(type(row))
    print(row)

<class 'sqlalchemy.engine.cursor.LegacyCursorResult'>
(5314, 1787, 930705, 96396, 12, 8033.0, 'B')
(5316, 1801, 930711, 165960, 36, 4610.0, 'A')
(6863, 9188, 930728, 127080, 60, 2118.0, 'A')
(5325, 1843, 930803, 105804, 36, 2939.0, 'A')
(7240, 11013, 930906, 274740, 60, 4579.0, 'A')
(6687, 8261, 930913, 87840, 24, 3660.0, 'A')
(7284, 11265, 930915, 52788, 12, 4399.0, 'A')
(6111, 5428, 930924, 174744, 24, 7281.0, 'B')
(7235, 10973, 931013, 154416, 48, 3217.0, 'A')
(5997, 4894, 931104, 117024, 24, 4876.0, 'A')
(7121, 10364, 931110, 21924, 36, 609.0, 'A')
(6077, 5270, 931122, 79608, 24, 3317.0, 'A')
(6228, 6034, 931201, 464520, 60, 7742.0, 'B')
(6356, 6701, 931208, 95400, 36, 2650.0, 'A')
(5523, 2705, 931208, 93888, 36, 2608.0, 'A')
(6456, 7123, 931209, 47016, 12, 3918.0, 'A')
(7104, 10320, 931213, 259740, 60, 4329.0, 'A')
(6820, 9034, 931216, 38148, 12, 3179.0, 'A')
(6876, 9236, 931221, 86616, 12, 7218.0, 'A')
(7097, 10266, 931223, 75624, 24, 3151.0, 'B')
(4959, 2, 940105, 80952, 24, 3373.0, 'A')
(6499, 7401, 940105, 80952, 24, 3373.0, 'A')
(5479, 2486, 940110, 24516, 12, 2043.0, 'A')
(5170, 1071, 940120, 253200, 60, 4220.0, 'C')
(6721, 8475, 940121, 21072, 24, 878.0, 'A')
(7259, 11111, 940131, 108144, 36, 3004.0, 'A')
(5285, 1603, 940206, 78936, 12, 6578.0, 'A')
(5189, 1166, 940207, 149040, 48, 3105.0, 'A')
(6650, 8073, 940217, 49320, 12, 4110.0, 'B')
(7226, 10940, 940223, 197748, 36, 5493.0, 'A')
(6087, 5313, 940227, 300660, 60, 5011.0, 'C')
(7262, 11135, 940301, 182628, 36, 5073.0, 'A')
(5519, 2694, 940308, 91632, 12, 7636.0, 'A')
(6577, 7753, 940311, 51696, 24, 2154.0, 'A')
(6509, 7445, 940315, 55368, 24, 2307.0, 'A')
(6520, 7485, 940316, 91200, 24, 3800.0, 'A')
(6699, 8330, 940330, 7656, 24, 319.0, 'A')
(6336, 6555, 940331, 212400, 36, 5900.0, 'A')
(7055, 10079, 940406, 167100, 60, 2785.0, 'C')
(6103, 5385, 940407, 149340, 60, 2489.0, 'C')
(6202, 5891, 940418, 65184, 12, 5432.0, 'A')
(7066, 10131, 940502, 215388, 36, 5983.0, 'B')
(6696, 8321, 940509, 89040, 60, 1484.0, 'C')
(6072, 5256, 940510, 193968, 36, 5388.0, 'A')
(5130, 813, 940511, 24312, 12, 2026.0, 'A')
(5568, 2933, 940517, 272520, 60, 4542.0, 'C')
(6678, 8173, 940520, 80340, 12, 6695.0, 'A')
(6998, 9833, 940521, 97632, 12, 8136.0, 'A')
(6580, 7769, 940522, 196080, 48, 4085.0, 'A')
(6316, 6473, 940526, 76908, 12, 6409.0, 'B')
(6512, 7454, 940526, 63312, 48, 1319.0, 'A')
(6407, 6930, 940526, 25944, 24, 1081.0, 'A')
(5002, 173, 940531, 104808, 12, 8734.0, 'A')
(6647, 8051, 940601, 208320, 48, 4340.0, 'A')
(7137, 10439, 940603, 151560, 24, 6315.0, 'A')
(6903, 9337, 940604, 52128, 24, 2172.0, 'A')
(5918, 4576, 940604, 300204, 36, 8339.0, 'A')
(6642, 8027, 940605, 77640, 12, 6470.0, 'A')
(6210, 5927, 940606, 87216, 48, 1817.0, 'B')
(6279, 6273, 940607, 87360, 24, 3640.0, 'A')
(7249, 11065, 940612, 69360, 48, 1445.0, 'A')
(6736, 8558, 940614, 288360, 60, 4806.0, 'C')
(6112, 5442, 940617, 174744, 24, 7281.0, 'B')
(5319, 1811, 940623, 239460, 60, 3991.0, 'C')
(6596, 7844, 940625, 91584, 24, 3816.0, 'A')
(5837, 4260, 940629, 244560, 60, 4076.0, 'C')
(5657, 3354, 940705, 4980, 12, 415.0, 'A')
(5533, 2762, 940705, 111384, 24, 4641.0, 'A')
(6232, 6051, 940708, 276660, 36, 7685.0, 'B')
(6888, 9265, 940711, 39576, 12, 3298.0, 'A')
(6066, 5228, 940711, 173808, 24, 7242.0, 'A')
(5549, 2824, 940716, 50460, 60, 841.0, 'C')
(5060, 426, 940719, 252060, 60, 4201.0, 'D')
(6004, 4937, 940723, 143904, 24, 5996.0, 'A')
(5126, 790, 940724, 208128, 48, 4336.0, 'B')
(7220, 10911, 940728, 131292, 36, 3647.0, 'A')
(6668, 8129, 940730, 74736, 36, 2076.0, 'A')
(5395, 2176, 940730, 299088, 36, 8308.0, 'B')
(6836, 9093, 940803, 189300, 60, 3155.0, 'C')
(6064, 5215, 940804, 14628, 12, 1219.0, 'A')
(6919, 9403, 940805, 120888, 36, 3358.0, 'A')
(6841, 9104, 940807, 172080, 48, 3585.0, 'A')
(6038, 5120, 940810, 323472, 48, 6739.0, 'A')
(6729, 8519, 940811, 74688, 12, 6224.0, 'A')
(7198, 10788, 940823, 45768, 12, 3814.0, 'A')
(6686, 8260, 940825, 224604, 36, 6239.0, 'A')
(5836, 4259, 940827, 79632, 24, 3318.0, 'A')
(7061, 10105, 940827, 121896, 24, 5079.0, 'A')
(5595, 3050, 940902, 82896, 12, 6908.0, 'A')
(5723, 3674, 940910, 23628, 12, 1969.0, 'A')
(6120, 5481, 940911, 209184, 48, 4358.0, 'A')
(6895, 9307, 940919, 41904, 12, 3492.0, 'A')
(5882, 4427, 940926, 87816, 12, 7318.0, 'A')
(5754, 3834, 940928, 23052, 12, 1921.0, 'A')
(6594, 7824, 940928, 189696, 24, 7904.0, 'B')
(6738, 8566, 940929, 230220, 36, 6395.0, 'B')
(6624, 7965, 940930, 71460, 12, 5955.0, 'A')
(6216, 5952, 940930, 141240, 24, 5885.0, 'A')
(6229, 6040, 941002, 11736, 24, 489.0, 'A')
(5887, 4448, 941003, 192744, 36, 5354.0, 'A')
(6808, 8982, 941012, 227880, 36, 6330.0, 'A')
(6297, 6363, 941025, 17508, 12, 1459.0, 'A')
(5161, 1012, 941028, 98184, 24, 4091.0, 'A')
(5390, 2167, 941030, 170256, 24, 7094.0, 'A')
(6150, 5622, 941102, 83016, 12, 6918.0, 'A')
(6223, 5991, 941103, 61056, 48, 1272.0, 'A')
(5032, 290, 941103, 123696, 48, 2577.0, 'A')
(6253, 6148, 941104, 59760, 24, 2490.0, 'A')
(6460, 7133, 941106, 48672, 36, 1352.0, 'A')
(6645, 8041, 941106, 140400, 36, 3900.0, 'A')
(5176, 1106, 941112, 192552, 24, 8023.0, 'B')
(5269, 1527, 941119, 164052, 36, 4557.0, 'B')
(5351, 1978, 941204, 205200, 36, 5700.0, 'A')
(5861, 4337, 941208, 51408, 24, 2142.0, 'A')
(5450, 2345, 941211, 199680, 60, 3328.0, 'C')
(7142, 10451, 941219, 482940, 60, 8049.0, 'D')
(6306, 6425, 941220, 36684, 12, 3057.0, 'A')
(6272, 6226, 941220, 398640, 60, 6644.0, 'C')
(5044, 344, 941221, 100980, 60, 1683.0, 'C')
(5576, 2962, 941221, 31248, 12, 2604.0, 'A')
(7192, 10738, 941221, 115992, 36, 3222.0, 'A')
(5739, 3747, 950102, 76380, 12, 6365.0, 'A')
(6526, 7523, 950103, 288468, 36, 8013.0, 'A')
(5624, 3166, 950103, 177744, 48, 3703.0, 'D')
(6244, 6118, 950108, 270648, 36, 7518.0, 'B')
(5131, 816, 950108, 48624, 24, 2026.0, 'A')
(6960, 9640, 950111, 76416, 24, 3184.0, 'A')
(6358, 6715, 950114, 137880, 60, 2298.0, 'D')
(5418, 2245, 950116, 347952, 48, 7249.0, 'C')
(6598, 7857, 950118, 68112, 12, 5676.0, 'A')
(5464, 2419, 950130, 95808, 12, 7984.0, 'A')
(6591, 7819, 950202, 20832, 48, 434.0, 'C')
(5724, 3678, 950205, 316140, 60, 5269.0, 'D')
(6315, 6472, 950206, 43164, 12, 3597.0, 'A')
(5876, 4413, 950208, 221280, 48, 4610.0, 'C')
(6986, 9750, 950211, 151728, 48, 3161.0, 'D')
(6294, 6353, 950212, 79920, 60, 1332.0, 'C')
(5132, 817, 950217, 538500, 60, 8975.0, 'C')
(5877, 4414, 950223, 97224, 24, 4051.0, 'A')
(6227, 6030, 950304, 28248, 24, 1177.0, 'A')
(7241, 11021, 950304, 168984, 24, 7041.0, 'B')
(6737, 8564, 950311, 76680, 24, 3195.0, 'A')
(7004, 9869, 950315, 331560, 60, 5526.0, 'C')
(6169, 5700, 950316, 103680, 60, 1728.0, 'D')
(5208, 1247, 950316, 99696, 48, 2077.0, 'D')
(6694, 8316, 950319, 134784, 24, 5616.0, 'A')
(5599, 3064, 950321, 15420, 12, 1285.0, 'A')
(6546, 7607, 950327, 31728, 24, 1322.0, 'A')
(5414, 2228, 950329, 185952, 48, 3874.0, 'C')
(5453, 2361, 950401, 156672, 36, 4352.0, 'A')
(5740, 3752, 950402, 18564, 12, 1547.0, 'A')
(5804, 4079, 950405, 158976, 48, 3312.0, 'C')
(6745, 8625, 950410, 47304, 24, 1971.0, 'A')
(6950, 9591, 950411, 104712, 24, 4363.0, 'A')
(6996, 9828, 950413, 126600, 24, 5275.0, 'A')
(5352, 1993, 950415, 68400, 12, 5700.0, 'B')
(6151, 5628, 950425, 225420, 60, 3757.0, 'C')
(5310, 1762, 950428, 248148, 36, 6893.0, 'A')
(5045, 347, 950501, 187224, 24, 7801.0, 'B')
(6929, 9472, 950508, 36396, 12, 3033.0, 'A')
(5151, 960, 950524, 189060, 60, 3151.0, 'C')
(5212, 1256, 950529, 71064, 36, 1974.0, 'A')
(5138, 854, 950530, 87216, 48, 1817.0, 'C')
(5713, 3629, 950530, 158760, 60, 2646.0, 'C')
(6704, 8377, 950601, 417060, 60, 6951.0, 'C')
(6474, 7190, 950606, 63360, 60, 1056.0, 'C')
(6676, 8159, 950613, 29784, 24, 1241.0, 'A')
(6965, 9656, 950613, 139536, 24, 5814.0, 'A')
(6725, 8489, 950623, 265320, 36, 7370.0, 'A')
(7166, 10630, 950624, 198240, 24, 8260.0, 'A')
(7138, 10440, 950703, 60000, 60, 1000.0, 'C')
(5970, 4774, 950709, 465072, 48, 9689.0, 'C')
(6157, 5650, 950710, 98592, 24, 4108.0, 'A')
(6153, 5632, 950725, 285600, 60, 4760.0, 'C')
(5693, 3489, 950801, 44088, 24, 1837.0, 'A')
(5922, 4580, 950805, 20220, 12, 1685.0, 'A')
(5959, 4727, 950811, 107640, 24, 4485.0, 'A')
(5980, 4825, 950818, 21396, 12, 1783.0, 'A')
(6764, 8776, 950826, 33984, 48, 708.0, 'C')
(5237, 1375, 950829, 45336, 24, 1889.0, 'A')
(6726, 8492, 950903, 85860, 60, 1431.0, 'C')
(6933, 9493, 950909, 188688, 48, 3931.0, 'C')
(5145, 915, 950916, 309552, 48, 6449.0, 'C')
(7008, 9897, 950922, 36168, 12, 3014.0, 'A')
(7227, 10942, 951002, 314520, 60, 5242.0, 'C')
(6600, 7861, 951008, 21852, 36, 607.0, 'A')
(6712, 8405, 951014, 266220, 60, 4437.0, 'C')
(7057, 10093, 951020, 231696, 36, 6436.0, 'A')
(7176, 10663, 951028, 260028, 36, 7223.0, 'A')
(7304, 11349, 951029, 419880, 60, 6998.0, 'C')
(6362, 6738, 951031, 37908, 12, 3159.0, 'A')
(5880, 4423, 951031, 73836, 36, 2051.0, 'A')
(6535, 7546, 951102, 41952, 12, 3496.0, 'A')
(5449, 2343, 951104, 99336, 24, 4139.0, 'A')
(6342, 6609, 951112, 60156, 36, 1671.0, 'B')
(5409, 2218, 951118, 182040, 60, 3034.0, 'C')
(6955, 9627, 951122, 244368, 48, 5091.0, 'C')
(6985, 9731, 951122, 113796, 36, 3161.0, 'A')
(5125, 789, 951123, 73056, 48, 1522.0, 'C')
(5805, 4081, 951128, 137904, 24, 5746.0, 'B')
(6185, 5774, 951128, 31176, 24, 1299.0, 'A')
(7243, 11042, 951204, 217152, 36, 6032.0, 'A')
(6403, 6924, 951205, 194880, 48, 4060.0, 'C')
(6578, 7765, 951211, 27984, 12, 2332.0, 'A')
(5413, 2227, 951212, 92976, 24, 3874.0, 'A')
(6949, 9583, 951212, 104712, 24, 4363.0, 'A')
(6545, 7606, 951212, 191880, 60, 3198.0, 'C')
(6178, 5742, 951216, 232560, 48, 4845.0, 'C')
(5160, 1011, 951218, 204000, 60, 3400.0, 'C')
(6785, 8899, 951225, 125340, 60, 2089.0, 'C')
(6540, 7562, 951231, 309600, 48, 6450.0, 'C')
(6589, 7815, 960101, 189696, 24, 7904.0, 'A')
(5900, 4503, 960101, 135360, 48, 2820.0, 'C')
(5999, 4907, 960103, 98832, 48, 2059.0, 'C')
(6043, 5126, 960111, 20352, 48, 424.0, 'C')
(5482, 2496, 960112, 165120, 60, 2752.0, 'C')
(7263, 11138, 960119, 89880, 24, 3745.0, 'A')
(6013, 4995, 960203, 128988, 36, 3583.0, 'D')
(5750, 3804, 960208, 63252, 12, 5271.0, 'A')
(6027, 5066, 960210, 61656, 24, 2569.0, 'B')
(6303, 6400, 960212, 72408, 24, 3017.0, 'B')
(7213, 10884, 960213, 113544, 36, 3154.0, 'C')
(6659, 8092, 960220, 56100, 60, 935.0, 'C')
(6175, 5735, 960221, 290700, 60, 4845.0, 'D')
(5610, 3112, 960224, 123216, 48, 2567.0, 'C')
(5563, 2912, 960229, 380160, 60, 6336.0, 'C')
(5989, 4852, 960304, 213300, 36, 5925.0, 'C')
(6698, 8327, 960310, 247728, 48, 5161.0, 'C')
(5312, 1772, 960313, 202788, 36, 5633.0, 'C')
(7189, 10728, 960321, 154656, 48, 3222.0, 'C')
(6816, 9017, 960326, 100224, 48, 2088.0, 'D')
(6137, 5574, 960410, 44628, 12, 3719.0, 'A')
(5128, 808, 960411, 215616, 48, 4492.0, 'D')
(5470, 2456, 960415, 200976, 48, 4187.0, 'C')
(5593, 3037, 960418, 277884, 36, 7719.0, 'D')
(5350, 1967, 960421, 249312, 48, 5194.0, 'C')
(6063, 5213, 960425, 320976, 48, 6687.0, 'D')
(6501, 7418, 960429, 30276, 12, 2523.0, 'B')
(5452, 2352, 960429, 49440, 60, 824.0, 'C')
(4961, 19, 960429, 30276, 12, 2523.0, 'B')
(4973, 67, 960502, 165960, 24, 6915.0, 'A')
(6190, 5794, 960506, 123600, 60, 2060.0, 'C')
(6715, 8411, 960506, 220620, 60, 3677.0, 'C')
(5892, 4462, 960514, 66480, 24, 2770.0, 'B')
(6550, 7614, 960518, 320592, 48, 6679.0, 'C')
(5706, 3608, 960524, 161496, 36, 4486.0, 'C')
(5148, 940, 960529, 284280, 60, 4738.0, 'C')
(6734, 8547, 960530, 173016, 36, 4806.0, 'C')
(6109, 5422, 960603, 368880, 60, 6148.0, 'C')
(6961, 9645, 960606, 176148, 36, 4893.0, 'C')
(6810, 9006, 960608, 186384, 48, 3883.0, 'C')
(5494, 2572, 960613, 360000, 48, 7500.0, 'C')
(5311, 1766, 960615, 30060, 60, 501.0, 'C')
(5445, 2322, 960629, 46320, 24, 1930.0, 'A')
(5301, 1698, 960706, 141948, 36, 3943.0, 'C')
(7034, 10001, 960711, 19044, 36, 529.0, 'C')
(6751, 8680, 960714, 85716, 36, 2381.0, 'C')
(6667, 8127, 960715, 155880, 24, 6495.0, 'A')
(6130, 5541, 960718, 32640, 48, 680.0, 'C')
(5429, 2268, 960718, 20196, 36, 561.0, 'C')
(5725, 3679, 960723, 444864, 48, 9268.0, 'C')
(6019, 5033, 960725, 11400, 12, 950.0, 'A')
(6421, 6985, 960725, 96768, 36, 2688.0, 'C')
(6992, 9790, 960727, 133968, 48, 2791.0, 'C')
(5136, 846, 960728, 187104, 24, 7796.0, 'A')
(5337, 1886, 960731, 162468, 36, 4513.0, 'C')
(5495, 2580, 960802, 89340, 60, 1489.0, 'C')
(7013, 9928, 960802, 89340, 60, 1489.0, 'C')
(6012, 4994, 960803, 258444, 36, 7179.0, 'C')
(6471, 7184, 960804, 155640, 24, 6485.0, 'A')
(6296, 6358, 960806, 270384, 48, 5633.0, 'C')
(7305, 11359, 960806, 54024, 12, 4502.0, 'A')
(6144, 5593, 960809, 44376, 12, 3698.0, 'A')
(6283, 6289, 960811, 85632, 48, 1784.0, 'C')
(7246, 11054, 960820, 148920, 60, 2482.0, 'C')
(5088, 544, 960822, 91152, 24, 3798.0, 'A')
(5988, 4851, 960822, 141648, 24, 5902.0, 'A')
(5282, 1583, 960824, 388512, 48, 8094.0, 'D')
(5938, 4650, 960825, 402000, 60, 6700.0, 'C')
(5606, 3084, 960828, 253512, 36, 7042.0, 'D')
(5385, 2143, 960909, 71460, 36, 1985.0, 'C')
(6865, 9199, 960911, 29448, 12, 2454.0, 'B')
(5586, 2994, 960914, 48744, 36, 1354.0, 'C')
(6302, 6397, 960916, 181020, 60, 3017.0, 'C')
(7194, 10762, 960917, 68832, 36, 1912.0, 'C')
(6461, 7136, 960919, 74124, 36, 2059.0, 'C')
(6732, 8533, 960919, 174048, 48, 3626.0, 'C')
(6613, 7926, 960922, 84120, 24, 3505.0, 'A')
(7036, 10019, 960925, 194940, 36, 5415.0, 'C')
(5897, 4476, 960925, 15192, 24, 633.0, 'A')
(6995, 9814, 960926, 96168, 12, 8014.0, 'A')
(5415, 2236, 960926, 139464, 36, 3874.0, 'D')
(7136, 10436, 960928, 54396, 36, 1511.0, 'C')
(7271, 11186, 961002, 392460, 60, 6541.0, 'C')
(5375, 2106, 961003, 101520, 12, 8460.0, 'A')
(5635, 3230, 961004, 77184, 36, 2144.0, 'C')
(6817, 9024, 961004, 70656, 48, 1472.0, 'C')
(5923, 4585, 961010, 64656, 48, 1347.0, 'C')
(5329, 1862, 961016, 396120, 60, 6602.0, 'C')
(6644, 8039, 961020, 93600, 24, 3900.0, 'A')
(6354, 6688, 961023, 22968, 36, 638.0, 'C')
(5082, 501, 961024, 262980, 60, 4383.0, 'C')
(6585, 7795, 961029, 372120, 60, 6202.0, 'C')
(6921, 9422, 961029, 86184, 12, 7182.0, 'A')
(5366, 2062, 961029, 86184, 12, 7182.0, 'A')
(5886, 4447, 961031, 192744, 36, 5354.0, 'C')
(5741, 3754, 961103, 68544, 24, 2856.0, 'A')
(4996, 132, 961106, 88440, 12, 7370.0, 'A')
(6015, 5001, 961109, 110112, 24, 4588.0, 'A')
(6309, 6434, 961111, 110136, 24, 4589.0, 'A')
(6073, 5263, 961112, 276300, 60, 4605.0, 'C')
(6006, 4948, 961115, 359760, 60, 5996.0, 'C')
(5611, 3115, 961115, 321180, 60, 5353.0, 'C')
(6944, 9548, 961115, 46176, 48, 962.0, 'C')
(7101, 10297, 961118, 421008, 48, 8771.0, 'C')
(6599, 7859, 961119, 72120, 12, 6010.0, 'A')
(6940, 9510, 961122, 228276, 36, 6341.0, 'C')
(5209, 1250, 961125, 182640, 48, 3805.0, 'C')
(5388, 2153, 961128, 61560, 12, 5130.0, 'A')
(6011, 4981, 961128, 179328, 48, 3736.0, 'C')
(5591, 3021, 961204, 155616, 48, 3242.0, 'C')
(7154, 10520, 961205, 417600, 60, 6960.0, 'C')
(7130, 10411, 961211, 123408, 24, 5142.0, 'A')
(6818, 9030, 961212, 155616, 48, 3242.0, 'C')
(5625, 3189, 961215, 222180, 60, 3703.0, 'D')
(6805, 8972, 961221, 45024, 48, 938.0, 'C')
(7233, 10963, 961225, 115812, 36, 3217.0, 'C')
(7308, 11362, 961227, 129408, 24, 5392.0, 'A')
(5895, 4473, 970103, 93960, 60, 1566.0, 'C')
(7122, 10365, 970104, 260640, 36, 7240.0, 'D')
(6173, 5724, 970108, 232560, 48, 4845.0, 'C')
(6142, 5591, 970121, 221880, 60, 3698.0, 'C')
(5358, 2018, 970121, 38520, 12, 3210.0, 'A')
(6095, 5358, 970124, 68340, 60, 1139.0, 'C')
(6878, 9242, 970124, 23184, 12, 1932.0, 'A')
(6554, 7637, 970129, 390096, 48, 8127.0, 'C')
(6793, 8931, 970130, 186300, 60, 3105.0, 'C')
(7286, 11271, 970131, 67320, 36, 1870.0, 'C')
(6076, 5269, 970202, 117420, 60, 1957.0, 'C')
(5134, 825, 970202, 53076, 12, 4423.0, 'A')
(5419, 2246, 970205, 415800, 60, 6930.0, 'C')
(6255, 6158, 970208, 247920, 48, 5165.0, 'D')
(5656, 3353, 970209, 146064, 24, 6086.0, 'C')
(6934, 9494, 970209, 116832, 12, 9736.0, 'A')
(6028, 5072, 970209, 317520, 60, 5292.0, 'C')
(6490, 7262, 970210, 73260, 60, 1221.0, 'C')
(6415, 6950, 970212, 475680, 48, 9910.0, 'C')
(7087, 10215, 970220, 44304, 24, 1846.0, 'C')
(5420, 2247, 970224, 72504, 24, 3021.0, 'C')
(5977, 4803, 970225, 59136, 48, 1232.0, 'C')
(6824, 9052, 970226, 71976, 24, 2999.0, 'D')
(5207, 1244, 970228, 35904, 48, 748.0, 'C')
(7115, 10351, 970304, 88704, 48, 1848.0, 'C')
(7250, 11069, 970304, 119136, 48, 2482.0, 'C')
(6010, 4969, 970306, 150180, 60, 2503.0, 'C')
(6088, 5317, 970307, 90180, 36, 2505.0, 'C')
(5682, 3455, 970307, 67464, 12, 5622.0, 'A')
(7201, 10807, 970307, 67464, 12, 5622.0, 'A')
(6938, 9504, 970310, 341280, 60, 5688.0, 'C')
(6875, 9235, 970313, 83280, 48, 1735.0, 'C')
(5953, 4715, 970314, 97176, 24, 4049.0, 'C')
(5942, 4681, 970315, 162624, 48, 3388.0, 'C')
(5382, 2134, 970317, 22932, 36, 637.0, 'C')
(6377, 6792, 970317, 17184, 12, 1432.0, 'A')
(5931, 4618, 970317, 66696, 24, 2779.0, 'D')
(5992, 4863, 970318, 76080, 12, 6340.0, 'A')
(5790, 4033, 970320, 84288, 48, 1756.0, 'C')
(6753, 8688, 970320, 67980, 12, 5665.0, 'A')
(6562, 7674, 970321, 94488, 24, 3937.0, 'C')
(7046, 10049, 970328, 91632, 12, 7636.0, 'A')
(5868, 4361, 970329, 90156, 12, 7513.0, 'A')
(5784, 3967, 970329, 84600, 36, 2350.0, 'D')
(5878, 4415, 970401, 74040, 12, 6170.0, 'A')
(5110, 675, 970401, 102240, 60, 1704.0, 'C')
(5210, 1252, 970401, 148140, 36, 4115.0, 'C')
(7230, 10954, 970402, 18720, 60, 312.0, 'C')
(5005, 176, 970410, 27456, 12, 2288.0, 'A')
(6871, 9225, 970413, 164256, 48, 3422.0, 'C')
(5363, 2051, 970422, 293880, 60, 4898.0, 'D')
(7253, 11079, 970426, 98304, 12, 8192.0, 'A')
(6055, 5181, 970428, 399120, 60, 6652.0, 'C')
(5072, 472, 970428, 196800, 24, 8200.0, 'D')
(6913, 9377, 970429, 99936, 24, 4164.0, 'C')
(6386, 6856, 970430, 124344, 36, 3454.0, 'C')
(5634, 3229, 970501, 39024, 12, 3252.0, 'A')
(5758, 3859, 970502, 307200, 60, 5120.0, 'D')
(6819, 9031, 970503, 50112, 24, 2088.0, 'C')
(7088, 10233, 970503, 239160, 60, 3986.0, 'C')
(5039, 314, 970503, 66840, 24, 2785.0, 'C')
(5532, 2754, 970504, 335280, 48, 6985.0, 'C')
(6037, 5118, 970504, 53232, 48, 1109.0, 'C')
(6322, 6510, 970506, 76992, 24, 3208.0, 'C')
(6887, 9263, 970508, 39576, 12, 3298.0, 'A')
(6660, 8094, 970509, 220428, 36, 6123.0, 'C')
(5451, 2350, 970511, 159744, 48, 3328.0, 'C')
(6014, 4999, 970518, 165168, 36, 4588.0, 'C')
(5556, 2872, 970519, 268320, 60, 4472.0, 'C')
(6346, 6649, 970522, 100260, 60, 1671.0, 'C')
(5850, 4293, 970522, 164196, 36, 4561.0, 'C')
(5940, 4660, 970528, 106944, 24, 4456.0, 'C')
(7119, 10361, 970602, 86880, 12, 7240.0, 'A')
(5253, 1447, 970603, 100080, 48, 2085.0, 'C')
(6851, 9138, 970603, 272220, 60, 4537.0, 'D')
(6695, 8320, 970604, 309660, 60, 5161.0, 'C')
(6908, 9353, 970608, 188616, 24, 7859.0, 'C')
(7255, 11096, 970609, 213300, 60, 3555.0, 'C')
(5674, 3418, 970610, 207264, 48, 4318.0, 'C')
(6278, 6265, 970610, 87360, 24, 3640.0, 'C')
(5486, 2516, 970613, 466608, 48, 9721.0, 'C')
(5174, 1093, 970613, 385104, 48, 8023.0, 'C')
(6621, 7957, 970614, 42900, 12, 3575.0, 'A')
(6313, 6461, 970615, 150912, 36, 4192.0, 'C')
(6435, 7045, 970616, 288720, 48, 6015.0, 'C')
(6970, 9677, 970617, 31620, 60, 527.0, 'C')
(6310, 6440, 970617, 34572, 12, 2881.0, 'A')
(5932, 4626, 970618, 33348, 12, 2779.0, 'A')
(6877, 9241, 970619, 285240, 60, 4754.0, 'C')
(6763, 8772, 970619, 88272, 48, 1839.0, 'C')
(7085, 10202, 970619, 305424, 48, 6363.0, 'C')
(7049, 10063, 970624, 233424, 36, 6484.0, 'C')
(6959, 9633, 970630, 59448, 24, 2477.0, 'D')
(5214, 1270, 970701, 74772, 36, 2077.0, 'C')
(6350, 6678, 970709, 294384, 48, 6133.0, 'C')
(5063, 442, 970710, 357840, 48, 7455.0, 'D')
(5041, 319, 970711, 369000, 60, 6150.0, 'C')
(5086, 525, 970716, 210384, 48, 4383.0, 'C')
(6942, 9513, 970716, 18324, 12, 1527.0, 'A')
(5270, 1528, 970721, 191088, 48, 3981.0, 'C')
(6705, 8381, 970725, 333648, 48, 6951.0, 'D')
(7051, 10068, 970728, 77808, 12, 6484.0, 'A')
(6758, 8742, 970729, 33144, 12, 2762.0, 'A')
(6249, 6138, 970730, 67608, 24, 2817.0, 'C')
(5808, 4099, 970731, 41856, 48, 872.0, 'C')
(5377, 2116, 970804, 92400, 12, 7700.0, 'A')
(5446, 2334, 970804, 48312, 24, 2013.0, 'C')
(5856, 4320, 970809, 51360, 12, 4280.0, 'B')
(4986, 97, 970810, 102876, 12, 8573.0, 'A')
(7001, 9859, 970810, 300600, 60, 5010.0, 'C')

retrieve data from MYSQL into Pandas Data Frame

In [12]:
query="SELECT count(*) as num from bank.loan"
bank_loans = pd.read_sql_query(query, db_connection)
bank_loans.head()

   num
0  682

Passing Parameter into a query

In [9]:
loan_id_threshold=5300
query = 'SELECT * FROM bank.loan where loan_id<'+str(loan_id_threshold)
filtered_loans = pd.read_sql_query(query, db_connection)
filtered_loans.head()

   loan_id  account_id    date  amount  duration  payments status
0     4959           2  940105   80952        24    3373.0      A
1     5170        1071  940120  253200        60    4220.0      C
2     5285        1603  940206   78936        12    6578.0      A
3     5189        1166  940207  149040        48    3105.0      A
4     5130         813  940511   24312        12    2026.0      A

# Create a database in Mysql and save a table from Pandas into that database.

#### Create Database and commit

In [13]:
db_connection.execute("create database if not exists lab_db_python_sql;")

In [14]:
db_connection.execute("commit")

#### Inspect the database

In [13]:
insp = sa.inspect(db_connection)
db_list = insp.get_schema_names()
print(db_list)

['bank', 'information_schema', 'lab_db', 'lab_db_python_sql', 'lab_db_python_sql2', 'lab_db_test_commands', 'lab_group_by_db', 'mysql', 'Olist', 'performance_schema', 'publications', 'sakila', 'skila_analytics', 'sys']

#### Write Pandas Data Frame to Database

In [14]:
test_table = pd.DataFrame({"a" : [1,2,3], "b" : [4,5,6]})
test_table

   a  b
0  1  4
1  2  5
2  3  6

In [16]:
test_table.to_sql(name="clean_df_test_2", con=db_connection, schema="lab_db_python_sql")

## off topic

#### Retreiving data from a View in a Sakilla database into pandas data frame

In [17]:
query="SELECT * FROM sakila.actor_info"
actor_info = pd.read_sql_query(query, db_connection)
actor_info

,actor_id,first_name,last_name,film_info
0,1,PENELOPE,GUINESS,Animation: ANACONDA CONFESSIONS; Children: LAN...
1,2,NICK,WAHLBERG,Action: BULL SHAWSHANK; Animation: FIGHT JAWBR...
2,3,ED,CHASE,"Action: CADDYSHACK JEDI, FORREST SONS; Classic..."
3,4,JENNIFER,DAVIS,Action: BAREFOOT MANCHURIAN; Animation: ANACON...
4,5,JOHNNY,LOLLOBRIGIDA,"Action: AMADEUS HOLY, GRAIL FRANKENSTEIN, RING..."
...,...,...,...,...
195,196,BELA,WALKEN,Action: FANTASY TROOPERS; Animation: LUKE MUMM...
196,197,REESE,WEST,Action: ANTITRUST TOMATOES; Animation: DOORS P...
197,198,MARY,KEITEL,"Action: FANTASY TROOPERS, FORREST SONS, HANDIC..."
198,199,JULIA,FAWCETT,"Action: BERETS AGENT; Animation: LUKE MUMMY, T..."
199,200,THORA,TEMPLE,Animation: CAROL TEXAS; Children: CHRISTMAS MO...

#### Calling Stored procedure from Sakilla Database

In [25]:
result = db_connection.execute('CALL sakila.film_in_stock(1, 1, @x);')
x = pd.read_sql_query('Select @x', db_connection)
x

   @x
0   4